config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  # The database queries or associations are being executed during the application's boot process,
  # before the database connection has been established, so rescue is used.
  begin
    ActiveAdmin.routes(self)
  rescue StandardError
    ActiveAdmin::DatabaseHitDuringLoad
  end
  devise_for :accounts
  get 'u/:username' => 'public#profile', as: :profile
  get '/saved_posts' => 'save_post#saved_posts'
  resources :communities, path: :r do
    resources :posts, path: :p do
      member do
        patch :close
        get :report
        post :poll_answers
      end
      resources :comments, only: [:create]
      resources :reports, only: [:create]
    end
  end

  get '/submit', to: 'posts#new', as: 'submit_new_community_post'

  post 'save_post/:id', to: 'save_post#create', as: 'save_post_path'

  resources :report_reasons
  resources :banned_users
  resources :subscriptions, only: %i[create destroy]

  post 'p/vote' => 'votes#create'

  get 'r/:id/mod' , to: 'communities#mod' , as: 'mod'

  get 'community_post_title_search', to: 'communities#community_post_title_search'
  get 'post_title_search', to: 'posts#post_title_search'
  get 'search_suggestions', to: 'communities#search_suggestions'
  get 'username_search', to: 'communities#username_search'

  match '/404', to: 'errors#not_found', via: :all
  get :autocomplete, to: 'communities#autocomplete'
  root to: 'public#index'
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: %i[slugged history finders]
  include ImageValidation

  validates :title, presence: { message: " can't be blank" }
  validate :acceptable_image
  validates_presence_of :account_id, :community_id
  validate :post_body_validation

  belongs_to :account
  belongs_to :community
 
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :save_posts
  has_rich_text :body
  has_many_attached :images, dependent: :destroy
  has_many :poll_answer

  scope :drafts, ->(account_id) { where(account_id: account_id, is_drafted: true) }

  def score
    if upvotes.positive? || downvotes.positive?
      upvotes.positive? ? (upvotes - downvotes) : (downvotes * -1)
    else
      0
    end
  end

  def should_generate_new_friendly_id?
    title_changed? || slug.blank?
  end

  def acceptable_image
    validate_multiple_images(images, :images)
  end

  def post_body_validation
    unless body.present? || images.present? || link.present? || poll_topic.present?
      errors.add(:base, "At least one of body or images or link or poll_topic must be present")
    end
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  before_action :set_post, only: %i[show update destroy increment_view_count close]

  # GET /posts
  def index
    @posts = Post.includes(:community, :account)
    render json: @posts, include: %i[community account]
  end

  def hot_posts
    @hot_posts = Post.includes(:community, :account).order(upvotes: :desc)
    render json: @hot_posts, include: %i[community account]
  end

  def new_posts
    @new_posts = Post.includes(:community, :account).order(created_at: :desc)
    render json: @new_posts, include: %i[community account]
  end

  def best_posts
    @best_posts = Post.includes(:community, :account).sort_by { |post| post.upvotes.to_f / (post.upvotes + post.downvotes + 1) }.reverse
    render json: @best_posts, include: %i[community account]
  end

  def top_posts
    @top_posts = Post.includes(:community, :account).order(view_count: :desc)
    render json: @top_posts, include: %i[community account]
  end
  
  def increment_view_count
    @post.view_count += 1
    @post.save
  end 

  # GET /posts/1
  def show
    increment_view_count
    render json: @post, include: %i[community account]
  end

  # POST /posts
  def create
    @post = Post.new(post_params)
    if @post.save
      render json: @post, status: :created
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /posts/1
  def update
    if @post.update(post_params)
      render json: @post
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # DELETE /posts/1
  def destroy
    @post.destroy
  end

  def navbar_search
    posts = Post.where('title LIKE ?', "%#{params[:q]}%").select(:id, :title, :community_id, :body, :account_id)
    communities = Community.where('name LIKE ?', "%#{params[:q]}%").select(:id, :name)
    accounts = Account.where('username LIKE ?', "%#{params[:q]}%").select(:id, :username)
    comments = Comment.where('message LIKE ?', "%#{params[:q]}%").select(:id, :message, :post_id, :account_id,
                                                                         :parent_id, :created_at)

    comments.each do |comment|
      post = posts.find { |p| p.id == comment.post_id }
      comment.community_id = post.community_id if post
      comment.post_title = post.title if post
    end

    comments.each do |comment|
      account = accounts.find { |acc| acc.id == comment.account_id }
      comment.username = account.username if account
    end
    data = {
      posts: { options: posts, type: 'post' },
      communities: { options: communities, type: 'community' },
      accounts: { options: accounts, type: 'account' },
      comments: { options: comments, type: 'comment' }
    }
    render json: data
  end

  def close
    @post.update(isclosed: 'true')
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.includes(:account, :community).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def post_params
    params.require(:post).permit(:account_id, :community_id, :title, :body, :upvotes, :downvotes, :total_comments,
                                 :is_drafted, :isclosed)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_account!, except: %i[index show]
  before_action :set_community, only: %i[new show create edit update destroy increment_view_count close poll_answers]
  before_action :set_post, only: %i[show edit update destroy increment_view_count close poll_answers]
  before_action :set_draft, only: %i[new edit update]
  before_action :find_my_communities, only: %i[new create edit update ]
  before_action :community_list
  before_action :cancel_check, only: [:update]
  def index
      @posts = Post.all
  end

  def show
    increment_view_count
    @comment = Comment.new
    @categories = ReportCategory.all
    @report = Report.new
  end

  def new
    @post = @community.posts.new
  end

  def create
    @drafts = Post.drafts(current_account.id)
    @post = Post.new post_params
    @post.account_id = current_account.id
    @post.is_drafted = !(params[:commit] == 'Publish')
    if @post.save
      if @post.is_drafted?
        flash[:notice] = t('draft.success')
        redirect_to new_community_post_path(@post.community_id)
      else
        flash[:notice] = t('post.success')
        redirect_to community_path(@post.community_id)
      end
    else
      flash[:alert] = t('form.required')
      render :new
    end
  end

  def edit; end

  def update
    @post.community_id = params[:community_id]
    @post.is_drafted = !(params[:commit] == 'Publish')
    if @post.update(post_params)
      if @post.is_drafted
        flash[:notice] = t('draft.success')
        redirect_back(fallback_location: edit_community_post_path)
      else
        flash[:notice] = t('post.success')
        redirect_to community_post_path(@post.community_id)
      end
    else
      flash[:alert] = t('form.required')
      render :edit
    end
  end

  def close
    @post.update(closed: 'true')
    flash[:notice] = t('post.close')
    redirect_back(fallback_location: root_path) 
  end

  def poll_answers 
    @poll_answers=PollAnswer.new(params.permit(:poll_answer, :community_id,:post_id))
    @poll_answers.account_id = current_account.id
    if @poll_answers.save 
      flash[:notice] = t('poll_answer.create')
    else
      redirect_to root_path
    end
  end

  def my_posts
    @my_posts = @community.posts.where(account_id: current_account.id)
  end

  def destroy
    return unless @post.destroy

    flash[:notice] = t('post.destroy')
    redirect_to root_path
  end

  def post_title_search
    @posts = Post.where("title ILIKE ?", "%#{params[:search]}%")
    @communities= Community.where("name ILIKE ?", "%#{params[:search]}%")
    @accounts=Account.where("username ILIKE ?", "%#{params[:search]}%")
    @comments=Comment.where("message  ILIKE ?", "%#{params[:search]}%")
  end


  private

  def increment_view_count
    @post.view_count += 1
    @post.save
  end

  def set_community
    @community = if params[:community_id]
                   Community.friendly.includes(:posts).find(params[:community_id])
                 else
                   Community.friendly.includes(:posts).find_by(params[:community_id])
                 end
  end

  def set_draft
    @drafts = Post.drafts(current_account.id).order(created_at: :desc)
  end

  def auth_subscriber
    return if Subscription.where(community_id: params[:community_id], account_id: current_account.id).any?

    redirect_to root_path, flash: { danger: 'You are not authorized to view this page' }
  end

  def post_params
    params.require(:post).permit(:title, :body,:link, :oc, :spoiler, :nsfw, :saved, :is_drafted, :closed,
                                 :community_id,:poll_topic,:option1,:option2,:option3,:option4,images: [])
  end

  

  def find_my_communities
    @subscriptions = Subscription.where(account_id: current_account.id).pluck(:community_id)
    @my_communities = Community.find(@subscriptions)
  end

  def cancel_check
    return unless params[:commit] == 'Cancel'

    redirect_to community_post_path(@post.community_id)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def form_submit_tag(form, button_text)
    form.submit button_text, class: 'text-white'
  end

  def authorized_upvote(upvote)
    return upvote ? 'upvote' : 'downvote' if signed_in?

    'login'
  end

  def image_format_validation(img)
    img.to_s.include?('.png') or img.to_s.include?('.jpg')
  end

  def link_is_valid(link)
    link.to_s.match(URI.regexp)
  end

  def selected_community(community)
    return '' if params[:post] == 'new'

    community.id
  end

  def answered(post_id)
    answered = PollAnswer.find_by(account_id: current_account.id, post_id: post_id)
  end
end

app/views/posts/_accounts_search.html.erb
<% if accounts.exists? %>
  <% accounts.each do |account| %>
    <div class="card post-card mb-3 shadow">
      <div class="row">
        <div class="col-sm-1">
          <%= display_profile_picture account, "post-list-profile-img-search", "profile-img.jpg" %>
        </div>
        <div class="card-body">
          <div class="d-flex card-text mt-1">
            <strong><%=link_to account.username,profile_path(account.username)%></strong>
            <p class="ml-1 text-muted ">
              <%= time_ago_in_words account.created_at %> ago</p>
            <br>
          </div>
          <p class="card-text"><%= account.bio %></p>
        </div>
      </div>
    </div>
  <%end%>
<%else%>
  <div class="card post-card mb-3 shadow">
    <center><%= image_tag "telescope-snoo.png" %>
      <h4><b>Hm... we couldn't find any results for "<%= params[:search]%>"</b></h4>
    </center><br>
  </div>
<%end%>

app/views/posts/_comments.html.erb
<script>
  window.onload = function() {
    var highlightedComment = document.querySelector('#highlighted-comment');
    if (highlightedComment) {
      highlightedComment.scrollIntoView({
        behavior: 'smooth'
      });
    }
  };
</script>
<div class = "comment">
  <% comments.each do |comment| %>
    <% if comment.account.profile_image.attached? %>
      <%= link_to image_tag(comment.account.profile_image, class: "small-pic float-left m-r-15"),profile_path(comment.account) %>
    <% else %>
      <img class="small-pic float-left m-r-15" src="https://www.iconpacks.net/icons/2/free-reddit-logo-icon-2436-thumb.png">
    <% end %>
    <strong><%= link_to comment.account.full_name, profile_path(comment.account.username), class: "text-dark" %></strong>
    <% if params[:highlight]==comment.message.to_plain_text%>
      <% text = comment.message.to_plain_text %>
      <br>
      <span id="highlighted-comment" class="mark"><%= text %></span>
    <%else%>
      <%=comment.message%>
    <%end%>
    <div class = "fl">
      <p class = "text-muted m-l-30"><%= time_ago_in_words comment.created_at %> ago </p>
      <% if !(@post.closed?) %>
        <a href = "#" class="comment-form-display">Reply</a>
      <% end %>
      <div class = "comment-form">
        <%= render partial: "comments/form", locals: {post: comment.post, parent: comment, comment_id: comment.id}%>
      </div>
    </div>
    <hr>
    <% if comment.replies.any? %>
      <% count = 0 %>
      <% comment.replies.each do |reply| %>
        <% count += 1 %>
        <div class = "sub-comment"><%= render partial: 'comments/reply', locals: { reply: reply, comment_id: reply.id } %></div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/posts/_content_warning_fields.html.erb
<div class="create-post m-3">
<div class="form-group">
    <ul class="ml-4 mr-4 pb-3 border-bottom">
      <li class="warning-nav-link" id="oc_warning"><i class='fa-solid fa-plus mr-1'></i>
        <%= form.check_box :oc, class: "d-none btn-check", id: "check", autocomplete: "off" %>
        OC
      </li>
      <li class="warning-nav-link" id="spoiler_warning"><i class='fa-solid fa-plus mr-1'></i>
        <%= form.check_box :spoiler, class: "d-none btn-check", id:"check", autocomplete: "off" %>
        Spoiler
      </li>
      <li class="warning-nav-link" id="nsfw_warning"><i class='fa-solid fa-plus mr-1'></i>
        <%= form.check_box :nsfw, class: "d-none btn-check", id:"check", autocomplete: "off" %>
        NSFW
      </li>
      <li class="warning-nav-link text-disabled" id="nsfw_warning"><i class='fa-solid fa-plus mr-1'></i>
        Flair
      </li>
    </ul>
  </div>
  </div>

app/views/posts/_form.html.erb
<div class="card rounded mb-3">
  <div class="row">
    <div class="col-12">
      <div class="">
        <ul class="nav">
          <li class="post-tab-nav-link flex-fill"><a data-toggle="tab" href="#posts_form"><i
                class='fa fa-rocket mr-2'></i> Posts</a></li>
          <li class="post-tab-nav-link flex-fill"><a data-toggle="tab" href="#images_form"><i
                class='fa fa-fire mr-2'></i> Images & Video</a></li>
          <li class="post-tab-nav-link flex-fill"><a data-toggle="tab" href="#link_form"><i class='fa fa-tag mr-2'></i>
              Link</a></li>
          <li class="post-tab-nav-link flex-fill "><a data-toggle="tab" href="#poll_form"><i
                class='fa fa-bar-chart mr-2'></i> Poll</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="tab-content">
  <div id="posts_form" class="tab-pane fade-in infinity active">
    <%= render partial: "post_form" %>
  </div>
  <div id="images_form" class="tab-pane fade infinity">
    <%= render partial: "images_form" %>
  </div>
  <div id="link_form" class="tab-pane fade infinity">
    <%= render partial: "link_form" %>
  </div>
  <div id="poll_form" class="tab-pane fade infinity">
    <%= render partial: "poll_form" %>
  </div>
</div>

app/views/posts/_images_form.html.erb
<%= form_for [@community, @post] do |form| %>
  <%= render 'post_column_community_title' %>
  <div class="create-post m-3">
    <div class="form-group">
      <b><%= form.label :images, "Upload Images :" %></b>
      <%= form.file_field :images,multiple: true, class: "form-control"%>
    </div>
  </div>
      <%= render 'content_warning_fields',form: form %>
  <div>
    <div class="float-right">
      <% unless params[:action] == 'edit' %>
      <div class="join-btn  create-post-btn mb-4">
        <%= form.submit "Save as draft", class: "text-white" %>
      </div>
      <% end %>
      <div class="join-btn create-post-btn mb-4">
        <%= form.submit "Publish", class: "text-white" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/_link_form.html.erb
<%= form_for [@community, @post] do |form| %>
  <%= render 'post_column_community_title' %>
  <div class="create-post m-3">
    <div class="form-group">
      <%= form.url_field :link, class: "form-control", placeholder: "Enter the URL"%>
    </div>
  </div>
      <%= render 'content_warning_fields',form: form %>
  <div>
    <div class="float-right">
      <% unless params[:action] == 'edit' %>
      <div class="join-btn  create-post-btn mb-4">
        <%= form.submit "Save as draft", class: "text-white" %>
      </div>
      <% end %>
      <div class="join-btn create-post-btn mb-4">
        <%= form.submit "Publish", class: "text-white" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/_list.html.erb
<% posts.each do |post| %>
  <% unless post.is_drafted %>
    <div class="card post-card mb-3 shadow">
      <div class="row m-0">
        <div class="col-1 m-0 vote-col text-center">
          <div id="vote-actions-<%= post.id %>" class="vote" data-id="<%= post.id %>">
            <div class="fa fa-arrow-up <%= authorized_upvote(true) %> <%= is_upvoted post %>"></div>
            <span class="font-weight-bold score"><%= post.score %></span>
            <div class="fa fa-arrow-down <%= authorized_upvote(false) %> <%= is_downvoted post %>"></div>
          </div>
        </div>
        <div class="col-11">
          <div class="row bg-white">
            <div class="col-10">
              <div class="d-flex post-list-head mt-2">
                <%= display_profile_picture post.community, "post-list-profile-img mr-1", "rediit-logo.png" %>
                <strong><%= link_to "r/"+post.community.name.capitalize, community_path(post.community), class: "text-dark" %>
                  . </strong>
                <p class="ml-1 text-muted">Posted by
                  <%= link_to "u/"+post.account.username.capitalize, profile_path(post.account.username), class: "text-muted" %>
                  <%= time_ago_in_words post.created_at %> ago</p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-12 d-flex post-title">
              <h5><%= link_to post.title, community_post_path(post.community, post), class: "text-dark" %></h5>
              <p class="flair-badge">Flair</p>
              <% if post.oc %>
                <p class="flair-badge bg-success">OC</p>
              <% end %>
              <% if post.spoiler %>
                <p class="flair-badge bg-warning">Spoiler</p>
              <% end %>
              <% if post.nsfw %>
                <p class="flair-badge bg-danger">NSFW</p>
              <% end %>
            </div>
          </div>
          <div class="row">
            <div class="list-post-img">
              <% if post.images.attached? && post.spoiler? %>
                <%= link_to community_post_path(post.community, post) do %>
                  <%= image_tag post.images[0] ,class:"sensitive-image" %>
                <% end %>
              <% elsif post.images.attached? && post.nsfw? %>
                <%= link_to community_post_path(post.community, post) do %>
                  <div class="margin">
                    <p class="col-12 sensitive-button">Click to see nsfw</p>
                  </div>
                <% end %>
              <% elsif post.images.attached? %>
                <%= link_to community_post_path(post.community, post) do %>
                  <%= image_tag post.images[0] %>
                <% end %>
              <% elsif post.poll_topic? &&  post.nsfw?%>
                <%= link_to community_post_path(post.community, post) do %>
                  <div class="margin">
                    <p class="col-12 sensitive-button">Click to see nsfw</p>
                  <% end %>
                  <%= render partial: 'posts/poll_answers_form',locals: {post: post ,community_id: post.community_id}%>
                </div>
              <% elsif post.poll_topic? &&  post.spoiler?%>
                <%= link_to community_post_path(post.community, post) do %>
                  <div class="margin">
                    <p class="col-12 sensitive-button">Click to see spoiler</p>
                  <% end %>
                  <%= render partial: 'posts/poll_answers_form',locals: {post: post ,community_id: post.community_id}%>
                </div>
              <% elsif post.poll_topic? %>
                <p class="col-12 "><%= post.poll_topic %></p>
                <div class="margin">
                  <%= render partial: 'posts/poll_answers_form',locals: {post: post ,community_id: post.community_id}%>
                </div>
              <%elsif link_is_valid(post.link)%>
                <%= link_to post.link,  url_for(post.link), target: "_blank",class: "col-12" %>
              <% elsif post.spoiler? %>
                <%= link_to community_post_path(post.community, post) do %>
                  <div class="margin">
                    <p class="col-12 sensitive-button">Click to see spoiler</p>
                  </div>
                <% end %>
              <% elsif post.nsfw? %>
                <%= link_to community_post_path(post.community, post) do %>
                  <div class="margin">
                    <p class="col-12 sensitive-button">Click to see nsfw</p>
                  </div>
                <% end %>
              <% elsif image_format_validation(post.body) %>
                <%=post.body%>
              <%else%>
                <p class="col-12 "><%= post.body.to_plain_text.truncate(30) %></p>
              <% end %>
            </div>
          </div>
          <div class="row mt-1 mb-1">
            <div class="col-12 d-grid">
              <%= link_to community_post_path(post.community, post), class: "list-post-tab" do %>
                <i class="fa fa-comment mt-1"></i> <%= post.comments.size %> Comments
              <% end %>
              <%= link_to "#", class: "list-post-tab" do %>
                <i class="fa fa-share mt-1"></i> Share
              <% end %>
              <%= link_to "#", class: "list-post-tab saved", remote: true, id: "save-actions-"+post.id.to_s, "data-id"=>post.id do %>
                <div class="fa <%= is_saved post %> <%= authorized_save_post %> ">
                  <%= save_or_unsave post %>
                </div>
              <% end %>
              <%= link_to community_post_path(post.community, post), class: "list-post-tab" do %>
                <i class="fa fa-flag-o mt-1"></i> Report
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<%= render partial: "layouts/backtotop" %>

app/views/posts/_post_column_community_title.html.erb
<%= form_for [@community, @post] do |form| %>
    <div class="row">
      <div class="col-sm-12">
        <div class="card rounded mb-3">
          <div class="form-group">
            <%= label_tag :Community %>
            <%= form.select :community_id, @my_communities.collect {|option| [option.name, option.id]}, { prompt: "Choose a Community" }, {class: "search-input-navbar community_select", data: {autocomplete_url: search_suggestions_path}} %>
            <p class="text-danger"><%= error_msg(@post, :community_id)  %></p>
          </div>
        </div>
      </div>
    </div>
    <div class="card rounded mb-3">
      <div class="create-post m-3">
        <div class="form-group">
        <%= form.text_field :title, class: style_error_class(@post, :title, "form-control"), placeholder: :title, maxlength: 300%>
        <p class="text-danger"><%= error_msg(@post, :title)  %></p>
        </div>
      </div>
<%end%>

app/views/posts/_post_form.html.erb
<%= form_for [@community, @post] do |form| %>
  <%= render 'post_column_community_title' %>
  <div class="create-post m-3">
    <div class="form-group">
      <%= form.rich_text_area :body, class: "textarea", placeholder: "Text(optional)" %>
    </div>
  </div>
      <%= render 'content_warning_fields',form: form  %>
  <div>
    <div class="float-right">
      <% unless params[:action] == 'edit' %>
      <div class="join-btn  create-post-btn mb-4">
        <%= form.submit "Save as draft", class: "text-white" %>
      </div>
      <% end %>
      <div class="join-btn create-post-btn mb-4">
        <%= form.submit "Publish", class: "text-white" %>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/posts/_reactions.html.erb
<div class = "reactions">
  <% if signed_in? %>
    <% if(@post.account_id == current_account.id) %>
      <div class="btn btn-light">
        <i class="fa fa-edit"></i><%= link_to "Edit", edit_community_post_path %>
      </div>
      <div class="btn btn-light">
        <i class="fa fa-trash"></i><%= link_to "Destroy", community_post_path(@post.community,@post),
              method: :delete,
              data: { confirm: "Are you sure?" } %>
      </div>
      <% if !(@post.closed?) %>
        <div class="btn btn-light" id="close-link">
          <i class="fa fa-times"></i><%= link_to "Close", close_community_post_path(@post.community,@post), method: :patch %>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <div class = "btn btn-light"><i class="fa fa-comment"></i><%= @post.comments.count %> Comments </div>
  <button type="button" class="btn btn-light" data-toggle="modal" data-target="#myModal" remote = "true">
    <i class="far fa-flag"></i>Report
  </button>
</div>
<%= render partial: "report" %>

app/views/posts/_search_tab.html.erb
<div class="card">
  <div class="card p-2 pl-3 pr-3">
    <div class="row">
      <div class="col-8 p-2">
        <ul class="nav">
          <li class="tab-nav-link "><a data-toggle="tab" href="#posts">Posts</a></li>
          <li class="tab-nav-link"><a data-toggle="tab" href="#comments">Comments</a></li>
          <li class="tab-nav-link"><a data-toggle="tab" href="#communities">Communities</a></li>
          <li class="tab-nav-link"><a data-toggle="tab" href="#people">People</a></li>
          </ul>
      </div>
    </div>
  </div>
</div>

app/views/posts/poll_answers.html.erb
<h1>Sri</h2>

app/views/posts/post_title_search.html.erb
<div class="margin-search">
<%= render partial: "posts/search_tab"%>
  <div class="tab-content">
  <div id="posts" class="tab-pane fade-in infinity ">
  <br>
  <%= render partial: "posts/post_search" , locals: { posts: @posts }%>
  </div>
  <div id="comments" class="tab-pane fade infinity">
  <br>
  <%= render partial: "posts/comments_search", locals: { comments: @comments }%>
  </div>
  <div id="communities" class="tab-pane fade infinity">
  <br>
  <%= render partial: "posts/community_search", locals: { communities: @communities }%>
  </div>
  <div id="people" class="tab-pane fade infinity">
  <br>
  <%= render partial: "posts/accounts_search", locals: { accounts: @accounts }%>
  </div>
  </div>
</div>

  