config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  # The database queries or associations are being executed during the application's boot process,
  # before the database connection has been established, so rescue is used.
  begin
    ActiveAdmin.routes(self)
  rescue StandardError
    ActiveAdmin::DatabaseHitDuringLoad
  end
  devise_for :accounts
  get 'u/:username' => 'public#profile', as: :profile
  get '/saved_posts' => 'save_post#saved_posts'
  resources :communities, path: :r do
    resources :posts, path: :p do
      member do
        patch :close
        get :report
        post :poll_answers
      end
      resources :comments, only: [:create]
      resources :reports, only: [:create]
    end
  end

  get '/submit', to: 'posts#new', as: 'submit_new_community_post'

  post 'save_post/:id', to: 'save_post#create', as: 'save_post_path'

  resources :report_reasons
  resources :banned_users
  resources :subscriptions, only: %i[create destroy]

  post 'p/vote' => 'votes#create'

  get 'r/:id/mod' , to: 'communities#mod' , as: 'mod'

  get 'community_post_title_search', to: 'communities#community_post_title_search'
  get 'post_title_search', to: 'posts#post_title_search'
  get 'search_suggestions', to: 'communities#search_suggestions'
  get 'username_search', to: 'communities#username_search'

  match '/404', to: 'errors#not_found', via: :all
  get :autocomplete, to: 'communities#autocomplete'
  root to: 'public#index'
end

app/models/community.rb
class Community < ApplicationRecord
  extend FriendlyId
  include ImageValidation
  friendly_id :slug_candidates, use: %i[slugged history finders]

  has_many :accounts, through: :banned_users
  has_many :comments
  has_many :posts, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :account
  has_one_attached :profile_image
  has_one_attached :cover_image
  has_many :banned_users
  belongs_to :account

  validates_presence_of :summary, :name, :rules, :category
  validates :name, uniqueness: true
  validates :url, presence: true, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]) }
  validate :accept_proflie_image
  validate :accept_cover_image

  CATEGORIES = Category.pluck(:name)

  def validate_name
    return unless Community.where(name: name).exists?

    errors.add(:name, 'has already been taken please choose some other Community name')
  end

  def should_generate_new_friendly_id?
    name_changed? || slug.blank?
  end

  def slug_candidates
    [
      :name,
      %i[name category],
      %i[name category url]
    ]
  end

  def accept_proflie_image
    validate_image(profile_image, :profile_image)
  end

  def accept_cover_image
    validate_image(cover_image, :cover_image)
  end
end

app/controllers/api/v1/communities_controller.rb
class Api::V1::CommunitiesController < ApplicationController
  # before_action :authenticate_account!, except: [:index]
  before_action :set_community, only: %i[show update destroy]

  # GET /communities
  def index
    @communities = Community.all

    render json: @communities
  end

  # GET /communities/1
  def show
    render json: @community, include: %i[posts account subscriptions banned_users]
  end

  # POST /communities
  def create
    @community = Community.new(community_params)

    if @community.save
      render json: @community, status: :created
    else
      render json: @community.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /communities/1
  def update
    if @community.update(community_params)
      render json: @community
    else
      render json: @community.errors, status: :unprocessable_entity
    end
  end

  def joined_account_community
    ids = Subscription.where(community_id: params[:community_id]).pluck(:account_id)
    @joined_accounts = Account.where(id: ids).where('username LIKE ?', "%#{params[:q]}%").select(:id, :username)
    render json: @joined_accounts
  end

  def search_suggestions
    communities = Community.where('name LIKE ?', "%#{params[:q]}%").select(:id, :name)
    render json: { options: communities }
  end

  # DELETE /communities/1
  def destroy
    @community.destroy
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_community
    @community = Community.includes(:posts, :account, :subscriptions, :banned_users).find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def community_params
    params.permit(:name, :url, :rules, :summary, :total_members, :account_id, :profile_image, :cover_image, :category)
  end

  def check_if_banned
    banned_user = BannedUser.find_by(account_id: params[:account_id], community_id: params[:id])
    return if banned_user.nil?

    render json: { message: 'User Already Banned' }
  end
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController
  before_action :authenticate_account!, except: [:index]
  before_action :set_community, only: %i[show edit update destroy mod]
  before_action :community_list
  before_action :check_if_banned, only: [:show]
  after_action :count_post_for_this_week, only: [:index]

  def index
    count_post_for_this_week
    @categories = Community::CATEGORIES
    if(params.has_key?(:category))
      @communities = Community.where(category: params[:category]).order(created_at: :desc).page(params[:page]).per 7
    else
      @communities = Community.order(created_at: :desc).page(params[:page]).per 7
    end
    @random_category_communities = Community.where(category: @categories.sample).order("post_count_this_week desc").limit(5)
  end

  def show
    @community = Community.find(params[:id])
    @posts = @community.posts.limit(20).sort_by { |p| p.score }.reverse
    @subscriber_count = @community.subscribers.count
    @subscribed = account_signed_in? ? Subscription.where(community_id: @community.id,account_id: current_account.id).any? : false
    @subscription = Subscription.new
    @banned_users = BannedUser.all
  end

  def new
    @community = Community.new
  end

  def edit
    if @community.account_id == current_account.id
      render :new
    else
      redirect_to communities_path, notice: t('form.forbidden')
    end
  end

  def create
    @community = Community.new community_params
    @community.account_id = current_account.id
    if @community.save
      Subscription.create!(community_id: @community.id, account_id: current_account.id)
      redirect_to @community, notice: t('community.success')
    else
      flash[:alert] = t('form.required')
      render :new
    end
  end

  def update
    if @community.update(community_params)
      redirect_to @community, notice: t('community.updated')
    else
      flash[:alert] = t('form.required')
      render :new
    end
  end

  def destroy
    @community.destroy if @community
    redirect_to communities_path, notice: t('community.destroy')
  end

  def mod
    redirect_back(fallback_location: root_path) and return unless @community.account_id == current_account.id

    @banned_user = BannedUser.where(community_id: @community.id)
                             .order(created_at: :desc)
                             .page(params[:page])
                             .per 5
    @username = Account.pluck(:username).sort
  end

  def community_post_title_search
    @community = Community.find(params[:selected_community_id])
    @posts = @community.posts.where("title ILIKE ?", "%#{params[:search]}%")
    @all_posts=Post.where(community_id: params[:selected_community_id])
    if @all_posts.present?
      @posts_with_comments = Comment.joins(:post).where("comments.message ILIKE ? and posts.id in (?)", "%#{params[:search]}%", @all_posts.pluck(:id))
    else
      @posts_with_comments = []
    end
  end

  def search_suggestions
    communities = Community.where("name ILIKE ?", "%#{params[:q]}%").select(:id, :name)
    render json: communities
  end

  def username_search
    usernames = Account.where("username ILIKE ?", "%#{params[:q]}%").select(:id , :username)
    render json: usernames
  end

  private
  def community_params
    params.require(:community).permit(:name, :url, :summary, :rules, :category, :profile_image, :cover_image)
  end

  def count_post_for_this_week
    @communities = Community.all
    @communities.each do |community|
      community.post_count_this_week = 0
      @posts = community.posts
      @posts.each do |post|
        community.post_count_this_week += 1 if ((Time.now - post.updated_at).to_f / 1.day).floor < 7
      end
      community.save
    end
  end

  def check_if_banned
    community = Community.find(params[:id])
    banned_user = BannedUser.find_by(account_id: current_account.id, community_id: community.id)
    return if banned_user.nil?

    redirect_to '/403'
  end
end

app/views/communities/_ban_users.html.erb
<% new_banned_user %>
<div class="col-md-3 offset-md-4 mt-2 p-2 join-btn">
  <%= link_to "#", "data-toggle"=>"modal", "data-target"=>"#myModal" do %>
  <button type="button" class="pl-5 pr-5 join-btn" data-toggle="modal" data-target="#myModal"> Ban Users </button> 
  <% end %>
</div>
<div class="modal fade" id="myModal"  role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Ban a User:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for @banneduser do |form| %>
          <div class="form-group">
            <%= form.hidden_field :community_id, :value => @community.id, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= label_tag :Enter_User_Name %>
            <%= form.select :username,options_for_select(Account.all.collect {|account| [account.username, account.id]}), { include_blank: "Search by username" }, class: "search-input form-control" %>
          </div>
          <div class="form-group">
            <%= label_tag :Reason_For_Ban %>
          </div>
          <div>
            <%= form.select :reason, ["Spam","Personal Confidential Information","Threatening Harassing or inciting violence","Others"] %>
          </div>
          <div class="form-group">
            <%= label_tag :Note_to_include_in_ban_message %>
            <%= form.text_area :explanation, placeholder: "Reason they were Banned", class: "form-control" %>
          </div>
          <div class="form-group">
            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
            <%= form.submit "Ban user", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/communities/_banned_users.html.erb
<div class="card" style="width: 40rem;">
  <div class="card-header">Banned Users <i class="fa fa-info-circle text-primary ml-1"></i></div>
  <% if @banneduser.empty? %>
    <p>***No Banned Users***</p>
  <% else %>
    <% @banneduser.each do |user| %>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"> <%= user.username %> </li>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/communities/_banned_users_list.html.erb
<div class="card w-100">
  <div class="card-header">Banned Users <i class="fa fa-info-circle text-primary ml-1"></i></div>
  <% if @banned_user.empty? %>
    <Center>No Banned Users in this community</Center>
  <% else %>
    <% @banned_user.each do |user| %>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"> <%= link_to account_username(user), profile_path(account_username(user)) %> </li>
      </ul>
    <% end %>
  <% end %>
</div>

app/views/communities/_banusers.html.erb
<% new_banned_user %>
<div class="col-md-4 offset-md-4">
  <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#myModal"> Ban Users </button>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Ban a User:</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= form_for @banneduser do |form| %>
          <div class="form-group">
            <%= form.hidden_field :community_id, :value => @community.id, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= label_tag :Enter_User_Name %>
            <%= form.text_field :username, autocomplete: :off, class: "form-control search-input", placeholder: "Search by username" %>
          </div>
          <div class="form-group">
            <%= label_tag :Reason_For_Ban %>
          </div>
          <div>
            <%= form.select :reason, ["Spam","Personal Confidential Information","Threatening Harassing or inciting violence","Others"] %>
          </div>
          <div class="form-group">
            <%= label_tag :Note_to_include_in_ban_message %>
            <%= form.text_area :explanation, placeholder: "Reason they were Banned", class: "form-control" %>
          </div>
          <div class="form-group">
            <button type="button" class="btn btn-primary" data-dismiss="modal">Cancel</button>
            <%= form.submit "Ban user", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/communities/_communities_search_tab.html.erb
<div class="card">
  <div class="card p-2 pl-3 pr-3">
    <div class="row">
      <div class="col-8 p-2">
        <ul class="nav">
          <li class="tab-nav-link "><a data-toggle="tab" href="#posts">Posts</a></li>
          <li class="tab-nav-link"><a data-toggle="tab" href="#comments">Comments</a></li>
          </ul>
      </div>
    </div>
  </div>
</div>

app/views/communities/_community_error_notification.html.erb
<% if @community.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@community.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
      <% @community.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/communities/_communityerrorfile.html.erb
<% if @community.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@community.errors.count, "error") %> prohibited this user from being saved:</h2>
    <ul>
      <% @community.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/communities/_subscribe.html.erb
<%= form_for @subscription do |f| %>
  <%= f.hidden_field :community_id, value: community_id %>
  <%= f.submit "Join", :class=>"join-btn" %>
<% end %>

app/views/communities/_unsubscribe.html.erb
<%= link_to "Leave", subscription_path, method: :delete, class: "join-btn", :id=>"leave-btn" %>

app/views/communities/community_post_title_search.html.erb
<div class="margin-search">
<%= render partial: "communities/communities_search_tab"%>
  <div class="tab-content">
  <div id="posts" class="tab-pane fade-in infinity ">
  <br>
  <%= render partial: "posts/post_search" , locals: { posts: @posts }%>
  </div>
  <div id="comments" class="tab-pane fade infinity">
  <br>
  <%= render partial: "communities/communities_comments_search", locals: { posts_with_comments: @posts_with_comments }%>
  </div>
  </div>
</div>

  

app/views/communities/edit.html.erb
<div class="community_post pb-10">
  <div class="row">
    <div class="col-10">
      <div class="row new_post_head pb-1">
        <div class="col-10 p-0">
          <h5 class="">Edit Community</h5>
        </div>
      </div>
      <div class="row mt-3">
        <div class="col-12 p-0">
          <%= render partial: "form" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/communities/index.html.erb
<%= render partial: "layouts/backtotop" %>
<div class="container mb-4">
  <h3 class="text-dark">Today's Top Growing Communities</h3>
  <% if account_signed_in? %>
    <div class="float-right">
      <%= link_to "Create New Community", new_community_path, class: "btn btn-outline-primary" %>
    </div>
  <% end %>
  <p class="text-muted">Browse Reddit's top growing communities. Find the top communities in your favorite category.</p>
</div>
<div class="container">
  <div class="row">
    <div class="col-2">
      <div class="text-dark mb-3">
        <div class="list-group" id="list-tab" role="tablist">
          <li class="list-group-item text-white bg-secondary">Category</li>
          <% if !(params.has_key?(:category)) %>
            <%= link_to communities_path, class: "text-decoration-none" do %>
              <li class="list-group-item border-left border-secondary">All</li>
            <% end %>
          <% else %>
            <%= link_to communities_path, class: "text-decoration-none" do %>
              <li class="list-group-item">All</li>
            <% end %>
          <% end %>
          <% @categories.each do |category| %>
            <% if params[:category] == category %>
              <%= link_to communities_path(category: category), class: "text-decoration-none" do %>
                <li class="list-group-item border-left border-secondary"><%= category %></li>
              <% end %>
            <% else %>
              <%= link_to communities_path(category: category), class: "text-decoration-none" do %>
                <li class="list-group-item"><%= category %></li>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-7">
      <div class="text-dark mb-3">
        <div class="list-group" id="nav-tabContent">
          <li class="list-group-item text-white bg-secondary">Today's Top Growing in Communities</li>
          <div class="tab-pane active" id="all_communities" role="tabpanel">
            <% if @communities.size > 0 %>
              <div class = "infinity">
                <%= render partial: "list" %>
              </div>
              <div class = "infinite-scrolling">
                <%= link_to_next_page(@communities, "posts" , :remote => true) %>
              </div>
            <% else %>
              <h3 class="m-4">No communities to display.</h3>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-3">
      <div class="text-dark mb-3">
        <div class="list-group">
          <li class="list-group-item text-white bg-secondary">Top <%= @random_category %> Communities</li>
          <% if @random_category_communities.size > 0 %>
            <% @random_category_communities.each do |community| %>
              <%= link_to community.name, community, class:"list-group-item" %>
            <% end %>
          <% else %>
            <p class="m-3">No communities to display.</p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/communities/index.js.erb
$("<%=j render partial: "list"%>").appendTo($(".infinity"));
<% if @communities.last_page? %>
  $('.infinite-scrolling').remove();
<% else %>
  $('.infinite-scrolling').html("<%=j link_to_next_page(@communities, 'See more', :remote => true) %>");
<% end %>

app/views/communities/show.html.erb
  <% if @community.cover_image.attached? %>
  <%= image_tag(@community.cover_image, class: "cover-image") %>
<% else %>
  <%= image_tag("Cover-Image.jpg" ,class: "cover-image") %>
<% end %>
<div class="row">
  <div class="col-sm-1 mr-3">
    <%= display_profile_picture @community, "profile-pic", "profile-pic.png" %>
  </div>
  <div class="col-sm-10">
    <div class = "d-flex">
      <span class = "ml-4">
        <h3>/r/<%= @community.name.downcase %> : <%= @community.category.downcase %></h3>
      </span>
      <div class="ml-3 pl-2">
        <% unless @community.account_id == current_account.id %>
          <% if @subscribed %>
            <%= render partial: "communities/unsubscribe" %>
          <% else %>
            <%= render partial: "communities/subscribe", locals: { community_id: @community.id } %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="community-nav-tab">
  <ul class="nav">
    <li class="community-nav-link active"><a data-toggle="tab" href="#post">Posts</a></li>
  </ul>
</div>
<div class="community_post">
  <div class="row">
    <div class="col-sm-8">
      <% if @subscribed %>
        <%= render partial: "posts/create_post", locals: { community: @community } %>
      <% end %>
      <div class="tab-content">
        <div id="post" class="tab-pane fade-in active">
          <%= render partial: "posts/list", locals: { posts: @posts } %>
        </div>
        <div id="menu1" class="tab-pane fade">
          <h3>Menu 1</h3>
          <p>Some content in menu 1.</p>
        </div>
        <div id="menu2" class="tab-pane fade">
          <h3>Menu 2</h3>
          <p>Some content in menu 2.</p>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card p-2 bg-gradient">
        <p class="h6 pt-2 text-light">About this community</p>
        <% if @community.account_id == current_account.id %>
          <%= link_to "Mod-Tools", mod_path, class: "btn btn-primary"%>
        <% end %>
      </div>
      <div class="card p-3">
        <p class=""><%= @community.summary %></p>
        <p class="text-muted"><i class='mr-2 fa fa-birthday-cake'></i>Created
          <%= @community.created_at.strftime("%b %d, %Y") %></p>
        <div class="member">
          <p><%= pluralize @subscriber_count, "member" %></p>
        </div>
        <% if @subscribed %>
          <%= link_to "Create post", new_community_post_path(@community), :class=>"join-btn create-post-btn text-white" %>
        <% end %>
      </div>
      <div class="card mt-3 p-2 bg-gradient">
        <p class="h6 pt-2 text-light">r/<%= @community.name.downcase %> Rules</p>
      </div>
      <div class="card p-3">
        <%= simple_format @community.rules %>
      </div>
    </div>
  </div>