config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  # The database queries or associations are being executed during the application's boot process,
  # before the database connection has been established, so rescue is used.
  begin
    ActiveAdmin.routes(self)
  rescue StandardError
    ActiveAdmin::DatabaseHitDuringLoad
  end
  devise_for :accounts
  get 'u/:username' => 'public#profile', as: :profile
  get '/saved_posts' => 'save_post#saved_posts'
  resources :communities, path: :r do
    resources :posts, path: :p do
      member do
        patch :close
        get :report
        post :poll_answers
      end
      resources :comments, only: [:create]
      resources :reports, only: [:create]
    end
  end

  get '/submit', to: 'posts#new', as: 'submit_new_community_post'

  post 'save_post/:id', to: 'save_post#create', as: 'save_post_path'

  resources :report_reasons
  resources :banned_users
  resources :subscriptions, only: %i[create destroy]

  post 'p/vote' => 'votes#create'

  get 'r/:id/mod' , to: 'communities#mod' , as: 'mod'

  get 'community_post_title_search', to: 'communities#community_post_title_search'
  get 'post_title_search', to: 'posts#post_title_search'
  get 'search_suggestions', to: 'communities#search_suggestions'
  get 'username_search', to: 'communities#username_search'

  match '/404', to: 'errors#not_found', via: :all
  get :autocomplete, to: 'communities#autocomplete'
  root to: 'public#index'
end

app/models/account.rb
class Account < ApplicationRecord
  include ImageValidation

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable

  has_many :subscriptions
  has_many :communities, through: :subscriptions, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :save_posts
  has_one_attached :profile_image, dependent: :destroy
  has_many :banned_users

  validates_presence_of :first_name, :last_name, :username
  validates :username, uniqueness: true
  validates_format_of :first_name, :last_name, multiline: true, with: /^[a-z]+$/i
  validates_format_of :username, multiline: true, with: /^[a-z0-9]+$/i
  validate :acceptable_image

  def full_name
    "#{first_name} #{last_name}"
  end

  def upvoted_post_ids
    votes.where(upvote: true).pluck(:post_id)
  end

  def downvoted_post_ids
    votes.where(upvote: false).pluck(:post_id)
  end

  def acceptable_image
    validate_image(profile_image, :profile_image)
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/banned_user.rb
class BannedUser < ApplicationRecord
  belongs_to :account
  belongs_to :community
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :account
  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: 'parent_id', dependent: :destroy
  validates_presence_of :message, :account_id, :post_id
  has_rich_text :message
end

app/models/community.rb
class Community < ApplicationRecord
  extend FriendlyId
  include ImageValidation
  friendly_id :slug_candidates, use: %i[slugged history finders]

  has_many :accounts, through: :banned_users
  has_many :comments
  has_many :posts, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :account
  has_one_attached :profile_image
  has_one_attached :cover_image
  has_many :banned_users
  belongs_to :account

  validates_presence_of :summary, :name, :rules, :category
  validates :name, uniqueness: true
  validates :url, presence: true, format: { with: URI::DEFAULT_PARSER.make_regexp(%w[http https]) }
  validate :accept_proflie_image
  validate :accept_cover_image

  CATEGORIES = Category.pluck(:name)

  def validate_name
    return unless Community.where(name: name).exists?

    errors.add(:name, 'has already been taken please choose some other Community name')
  end

  def should_generate_new_friendly_id?
    name_changed? || slug.blank?
  end

  def slug_candidates
    [
      :name,
      %i[name category],
      %i[name category url]
    ]
  end

  def accept_proflie_image
    validate_image(profile_image, :profile_image)
  end

  def accept_cover_image
    validate_image(cover_image, :cover_image)
  end
end

app/models/poll.rb
class Poll < ApplicationRecord
    belongs_to :post
end

app/models/poll_answer.rb
class PollAnswer < ApplicationRecord
    belongs_to :account
    belongs_to :post
    belongs_to :community
end

app/models/post.rb
class Post < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: %i[slugged history finders]
  include ImageValidation

  validates :title, presence: { message: " can't be blank" }
  validate :acceptable_image
  validates_presence_of :account_id, :community_id
  validate :post_body_validation

  belongs_to :account
  belongs_to :community
 
  has_many :comments, dependent: :destroy
  has_many :reports, dependent: :destroy
  has_many :save_posts
  has_rich_text :body
  has_many_attached :images, dependent: :destroy
  has_many :poll_answer

  scope :drafts, ->(account_id) { where(account_id: account_id, is_drafted: true) }

  def score
    if upvotes.positive? || downvotes.positive?
      upvotes.positive? ? (upvotes - downvotes) : (downvotes * -1)
    else
      0
    end
  end

  def should_generate_new_friendly_id?
    title_changed? || slug.blank?
  end

  def acceptable_image
    validate_multiple_images(images, :images)
  end

  def post_body_validation
    unless body.present? || images.present? || link.present? || poll_topic.present?
      errors.add(:base, "At least one of body or images or link or poll_topic must be present")
    end
  end
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :post
  belongs_to :report_reason
  belongs_to :report_category
  belongs_to :account
end

app/models/report_reason.rb
class ReportReason < ApplicationRecord
  belongs_to :report_category
end

app/models/save_post.rb
class SavePost < ApplicationRecord
  belongs_to :account
  belongs_to :post
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :account
  belongs_to :community
end

app/models/un_ban_job.rb
class UnBanJob < ApplicationJob
    queue_as :default
  
    def perform_later(ban_user_id)
      ban_user = BanUser.find(ban_user_id)
      if  ban_user.duration > 0 && ban_user.days_since_creation >= ban_user.duration
        ban_user.destroy
      end
    end
end
  

app/models/vote.rb
class Vote < ApplicationRecord
  validates_uniqueness_of :account_id, scope: :post_id
  belongs_to :account
  belongs_to :post

  after_create :increment_vote, :add_karma
  after_destroy :decrement_vote, :remove_karma

  scope :vote, ->(value) { where('upvote=', value) }

  private

  def increment_vote
    field = upvote ? :upvotes : :downvotes
    post.increment!(field)
  end

  def decrement_vote
    field = upvote ? :upvotes : :downvotes
    post.decrement!(field)
  end

  def add_karma
    account.increment!(:karma)
  end

  def remove_karma
    account.decrement!(:karma)
  end

  def self.save_vote(new_vote, existing_vote)
    if new_vote.upvote == existing_vote.first&.upvote
      existing_vote.first.destroy
    else
      existing_vote.first&.destroy
      new_vote.save
    end
  end
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def form_submit_tag(form, button_text)
    form.submit button_text, class: 'text-white'
  end

  def authorized_upvote(upvote)
    return upvote ? 'upvote' : 'downvote' if signed_in?

    'login'
  end

  def image_format_validation(img)
    img.to_s.include?('.png') or img.to_s.include?('.jpg')
  end

  def link_is_valid(link)
    link.to_s.match(URI.regexp)
  end

  def selected_community(community)
    return '' if params[:post] == 'new'

    community.id
  end

  def answered(post_id)
    answered = PollAnswer.find_by(account_id: current_account.id, post_id: post_id)
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def is_upvoted(post)
    account_signed_in? && current_account.upvoted_post_ids.include?(post.id) ? ' active' : ''
  end

  def is_downvoted(post)
    account_signed_in? && current_account.downvoted_post_ids.include?(post.id) ? ' active' : ''
  end
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable?  %>
    <%= image_tag blob.representation(resize_to_limit: [ 400, 400 ]) %>
  <% end %>
 
</figure>

app/views/layouts/_backtotop.html.erb
<%= link_to "Top", '#', class: "top_btn", id: "myBtn" %>

app/views/layouts/_flash.html.erb
<script>
  toastr.options = {
    "closeButton": true
  };
  <% if flash[:notice] %>
    toastr["success"]("<%= flash[:notice] %>")
  <% end %>
  <% if flash[:alert] %>
    toastr["warning"]("<%= flash[:alert] %>")
  <% end %>
</script>

app/views/layouts/_navbar.html.erb
<script>
  $(document).ready(function () {
  var community_name = window.location.pathname.split('/').pop();
  if (window.location.href.startsWith("http://localhost:3000/r/" + community_name)) {
  $("#search-input-community").show();
  $("#search-input").hide();
  } else {
  $("#search-input-community").hide();
  $("#search-input").show();
  }
  document.getElementById("search-input").addEventListener("change", function () {
  let options = document.querySelectorAll("#options option");
  for (let option of options) {
  if (option.value === this.value) {
  let type = option.dataset.type;
  let selectedOption = document.querySelector('#options option[value="' + this.value + '"]');
  let communityId = selectedOption.dataset.id;
  document.getElementById("selected-community-id").value = communityId;
  window.location.href = (type === "community" ? "/r/" + communityId : "/u/" + this.value.substring(2));
  break;
  }
  }
  });
  });
</script >
<div class="p-1 bg-light mr-auto">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav">
      <%= image_tag 'rediit-logo.png', class: "navbar-brand", width: 35, height: 45%>
      <%= link_to "Reddit Clone", root_path, :class => "navbar-brand" %>
    </div>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav">
      <li class=" nav-item dropdown">
        <%= link_to "Home", root_path, :class => "nav-link dropdown-toggle", :id=>"navbarDropdown", "data-toggle"=>"dropdown" %>
        <div class="dropdown-menu myDropdown" aria-labelledby="navbarDropdown">
          <input type="text" placeholder="Filter.." class="myInput_mycommunities">
          <%= link_to "All Communities", communities_path, :class=>"dropdown-item" %>
          <%= link_to "Top Trending", communities_path, :class=>"dropdown-item"  %>
          <div class="mt-2 ml-3 mb-2 text-muted">My Communities</div>
          <%= link_to "Create a Community", new_community_path, :class=>"dropdown-item" %>
          <% if @communities.present? and account_signed_in? and !@subscribers.nil? %>
            <% @subscribers.each do |subscribe| %>
              <%= link_to community_path(subscribe.community), class:"dropdown-item" do %>
                <div class="d-flex">
                  <% if subscribe.community.profile_image.attached? %>
                    <%= image_tag(subscribe.community.profile_image, class: "community-icon") %>
                  <% else %>
                    <%= image_tag("profile-pic.png" ,class: "community-icon") %>
                  <% end %>
                  r/<%=subscribe.community.name %>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </li>
    </ul>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <li class="nav-item dropdown">
          <%= form_tag post_title_search_path, method: :get do %>
            <div class="nav-item dropdown">
             <%= text_field_tag :search, nil, id: "search-input", list: "options", placeholder: " Search Reddit" %>
              <datalist id="options">
                <%= content_tag :option, "Select Community or Username", value: "", disabled: true, selected: true %>
                <% Community.pluck(:name, :id).each do |name, id| %>
                  <%= content_tag :option, "r/#{name}", value: "r/#{name}", data: {type: "community",id:id }, id: "community-option" %>
                <% end %>
                <% if current_account.present? %>
                  <% current_user_id = current_account.id%>
                  <% Account.pluck(:username, :id).each do |username, id| %>
                    <% unless id == current_user_id %>
                      <%= content_tag :option, "u/#{username}", value: "u/#{username}", data: {type: "account" } , class: "account-option"%>
                    <% end %>
                  <% end %>
                <% end %>
              </datalist>
            <% end %>
          </li>
          <%= form_tag community_post_title_search_path, id: "search-input-community",method: :get do %>
            <div class="nav-item dropdown">
              <% community = Community.find_by(id: params[:id]) %>
              <% community_name = community.try(:name) %>
              <%= text_field_tag :search, params[:search], size: 35 ,class: "form-control", placeholder: "Search in \"#{community_name}\" Community", id: "search-input-community" %>
              <%= hidden_field_tag :selected_community_id, nil, id: "selected-community-id", value: params[:id] %>
            </div>
          <% end %>
        </ul>
      </div>
      <ul class="navbar-nav ">
        <% if account_signed_in? %>
          <div class="karma float-left mt-2 mr-1">
            <%= current_account.karma %>
            <li class="fa fa-star text-warning"></li>
          </div>
          <li class="nav-item dropdown float-left mr-5">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= display_profile_picture current_account, "community-icon", "profile-img.jpg" %>
              <%= current_account.username %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profile_path(current_account.username), class: "dropdown-item" %>
              <%= link_to "Settings", edit_account_registration_path, class: "dropdown-item" %>
              <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", new_account_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_account_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav >
</div >

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reddit Clone</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= javascript_pack_tag 'application' %>
  </head>
  <body>
    <%= render partial: "layouts/navbar" %>
    <%= yield %>
    <%= render partial: "layouts/flash" %>
  </body>
</html>